Feat/week compose4
NOW-SOPT-ANDROID/seokjun-lee pull request #11
Opened 2024-05-03 14:22 UTC by boiledEgg-s

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #10

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- API 통신을 통한 회원가입 기능 구현
- API 통신을 통한 로그인 기능 구현
- API 통신을 통한 내정보 기능 구현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
[compose_week4.webm](https://github.com/NOW-SOPT-ANDROID/seokjun-lee/assets/101652649/78a814d2-8954-4481-8ecf-8e9b231d1804)

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
막판 스퍼트 달리느라 코드가 좀 지저분합니다,, 차근차근 청소해보도록 하겠습니다!!!

2024-05-03 16:57 UTC, l2hyunwoo requested changes
안녕하세요 석준님. 안드로이드 파트 명예 OB 이현우입니다. 만나서 반갑습니다.

앞으로의 과제들에 대한 코드리뷰를 맡게 되었습니다. 고민해보시다가 궁금한 점이 있으시면 지식 공유방/디스코드 연락 해주세요. 대면/비대면 자유형식으로 추가 피드백 가능합니다.

우선 과제 어려우셨을텐데 빠르게 과제 수행해주신점 너무 좋습니다. 관련해서 추가적으로 피드백/질문 남긴 것들이 있습니다. 질문을 남긴 경우 코드에 문제가 있어서 질문이 남긴 것이 아니고 정말 석준님의 작성 의도가 궁금해서 남긴 것이니 이 점 참고해주시면 감사하겠습니다.

앞으로 잘 부탁드리겠습니다.

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/models/Follow.kt
> +)
Follow가 동사여서 어떤 대상을 지칭하는지 잘 모르겠네요. Follower 정도로 대상을 구체화하는 건 어떨까요?

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/SoptAppContainer.kt
>  }
AppContainer라는걸 따로 구현하시는 이유가 있을까요?

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/SoptAppContainer.kt
> +    lateinit var retrofitAfterLogin: AuthService
AuthService 타입의 객체인데 변수명만 보면 Retrofit 타입의 객체인 것 같네요. 이 부분 불일치 발생해서 사용하는쪽에서 에러 일으킬 확률이 높아질 것 같습니다.

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/SoptAppContainer.kt
> +            .baseUrl("https://reqres.in/")
위의 객체에서는 상수화를 하셨는데 이 URL은 상수화를 안 한 이유가 따로 있을까요?

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/SoptAppContainer.kt
> +        }
음....OkHttpClient는 레트로핏 객체가 만들어질때 생성되어서 같이 build되는걸로 알고 있는데 이렇게 함수를 설계하면 memberId를 바꾸기 위해서라면 새롭게 retrofit 객체를 생성해서 사용해야하지 않을까요? 변경이 너무 어려운 구조로 되어있는 것 같습니다.

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/network/ApiFactory.kt
> +    lateinit var retrofitAfterLogin: AuthService
이걸 따로 만드신 이유가 있을까요?

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/network/ApiFactory.kt
> +}
- 위의 authService도 public으로 열려있는데, mainService를 또 따로 만드신 이유가 있을까요
- lateinit var로 만드신 이유가 있을까요? 이와 같이 설계를 한다면 사용측에서 mainService 객체 언제든지 마음대로 바꿀 수 있습니다.

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeScreen.kt
> +        viewModel.fetchDatas(navController)
- 어떤 데이터를 말하는건가요? 함수의 이름이 직관적으로 작성되어있지 않아서 viewModel이 어떤 데이터를 가져오는지 이해하기가 어렵습니다.
- ViewModel 멤버 함수에 navController를 넘기는 이유가 무엇일까요? ViewModel이 가져야 하는 책임과 View쪽에서 가져야 하는 책임이 무엇인지 잘 생각해보시면 좋을 것 같습니다.

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeScreen.kt
> +        /*Image(
필요없는 코드들은 주석처리보단 삭제하시는 것을 권장드립니다.

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +)
- HomeState가 변경된걸 State 통해서 알려야할 때에는 객체 내 프로퍼티를 변경하는 것이 아니고 객체를 통째로 바꿔야 State가 이를 화면에 알려줍니다. 즉 지금 형태는 State 변경을 알리는데 효과가 없는 형태라고 볼 수 있습니다.
- nullable type은 타입 옆에 바로 ?를 붙이는게 가독성에 좋습니다.
- List는 emptyList()라는 함수를 지원해서 빈 컬렉션을 지원하는데 굳이 nullable이어야 하는 이유가 있나요?

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
>      val uiState: StateFlow<HomeUiState> = _uiState.asStateFlow()
state와 uiState는 뭐가 다른 것일까요?

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +            ?.getLiveData<String>(NAVIGATE_LOGIN_KEY)?.value
savedStateHandle이라는 걸 활용해서 ViewModel에서 직접 백스택 엔트리에 있는 값을 가져올 수 있습니다!

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +        authService.getMemberInfo().enqueue(object : Callback<ResponseMemberInfoDto> {
이 부분은 OkHttpClient만 구조를 바꾸면 개선할 수 있을 것 같습니다.

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +                        id = data?.data?.authenticationId ?: "",
```suggestion
                        id = data?.data?.authenticationId.orEmpty(),
```
라는 확장함수도 있습니다.

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +        val followList = followRepository.fetchFollow()
fetchFollow가 성공하는 경우에는 아래 로직이 실행이 잘 될텐데, 실패를 하면 어떻게 될까요?

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginScreen.kt
>      val uiState = viewModel.uiState.collectAsState()
```suggestion
    val uiState by viewModel.uiState.collectAsState()
```
를 사용하신다면

```kotlin
    LaunchedEffect(uiState.message) {
```

아래 함수를 좀 더 간편하게 바꿀 수 있습니다.

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginScreen.kt
>      viewModel.checkCurrentStack(context = context, navController = navController)
이 부분 역시 Side Effect 이기 때문에 LaunchedEffect 내에서 실행시키는 것을 권장드립니다.

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginScreen.kt
>      viewModel.checkCurrentStack(context = context, navController = navController)
+ 만약에 LaunchedEffect가 아닌 함수 본문에서 실행하면 어떤일이 발생될까요?

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginViewModel.kt
> +        _uiState.update { currentState ->
update라는 함수하고 value에다가 값 바꾸는 함수하고 어떤 점이 다르길래 update를 사용하게 된것인가요?

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginViewModel.kt
> +class LoginViewModel(): ViewModel() {
```suggestion
class LoginViewModel: ViewModel() {
```

생성자에 아무것도 안들어가면 괄호 지워도 됩니다.

2024-05-03 16:57 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginViewModel.kt
> +                }
서버 에러는 화면 상태에 영구적으로 지속되어야 하나요 아니면 한번만 보여지면 되나요? 이 경우도 다양하게 구현이 나눠지기 때문에 각 상황에서 화면을 어떻게 그릴지 대략적으로 생각을 해보시고 에러 상황/상태 정의를 하시는것이 좋습니다.

2024-05-05 11:34 UTC, youjin09222 approved these changes
역시 3조 에이스! 너무 잘하시네요👍👍

2024-05-05 11:38 UTC, chattymin requested changes
이번주도 고생하셨습니다!!
어렵고 생소한 과제였을텐데 야무지게 잘 해오셨네욥

2024-05-05 11:38 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/ui/screens/signup/SignUpViewModel.kt
> +        )
with가 아닌 다른 다른 scope함수를 사용한다면 내부에 있는 마지막 줄의 객체를 반환할 수 있답니다
return을 안써줘도 돼용~

2024-05-05 11:38 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +    private fun fetchMemberInfo(memberId: String = "66") {
테스트용으로 기본값을 넣어둔 것 같은데 나중에 이 함수를 호출할 때 기본값이 들어가 있다면 변수를 안넣어버리는 실수를 할 수가 있어용

테스트가 끝났다면 지워주세욥

2024-05-05 11:38 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +            Log.d(TAG, follow.toString())
log도 안쓰면 지워주기~!

2024-05-05 11:38 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +    }
이 친구는 어디에서 쓰이고 있는걸가용?

2024-05-05 13:15 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginScreen.kt
> +    }
오 LaunchedEffect 좋네요!
저도 적용해보겠습니다!

2024-05-05 13:33 UTC, boiledEgg-s commented
> 안녕하세요 석준님. 안드로이드 파트 명예 OB 이현우입니다. 만나서 반갑습니다.
> 
> 앞으로의 과제들에 대한 코드리뷰를 맡게 되었습니다. 고민해보시다가 궁금한 점이 있으시면 지식 공유방/디스코드 연락 해주세요. 대면/비대면 자유형식으로 추가 피드백 가능합니다.
> 
> 우선 과제 어려우셨을텐데 빠르게 과제 수행해주신점 너무 좋습니다. 관련해서 추가적으로 피드백/질문 남긴 것들이 있습니다. 질문을 남긴 경우 코드에 문제가 있어서 질문이 남긴 것이 아니고 정말 석준님의 작성 의도가 궁금해서 남긴 것이니 이 점 참고해주시면 감사하겠습니다.
> 
> 앞으로 잘 부탁드리겠습니다.

반갑습니다 현우님~ 엄청난 실력자라고 들었는데 많이 배우도록 하겠습니다!!!! 부족한 부분이 보이면 가감없이 리뷰 날려주세요^^ 잘 부탁드립니다 :)

2024-05-05 14:37 UTC, hyeumm approved these changes
매번 느끼지만 너무 잘하십니다.. 정말정말... 같은 YB라는게 안믿겨요...!!!....

2024-05-05 14:37 UTC, hyeumm commented on app/src/main/java/com/sopt/now/compose/ui/screens/profile/ProfileViewModel.kt
> +        })
!isSuccessful 상황에서는 아무 동작도 안하도록 설정하신게 맞나요?? 궁금해서 질문합니닷..!

2024-05-05 17:38 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/models/Follow.kt
> +)
넵 수정하겠습니다!!

2024-05-05 17:48 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/container/SoptAppContainer.kt
>  }
안드로이드에서 제공하는 컴포즈 학습 강의에서 데이터와 UI 레이어 분리, 그리고 뷰모델에서 데이터 레이어에 접근할 수 있게 하기 위해 저장소 구조를 "Application 클래스 안에 AppContainer, AppContainer 안에 저장소 객체들"과 같이 선언하더라구요. 

제대로 알아보고 했다기 보단 이런 식으로 안드로이드 권장 아키텍처가 구현된다고 배워서 써봤습니다!!
제가 참고했던 [강의링크](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-repository?hl=ko&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-5-pathway-2%3Fhl%3Dko%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-repository#0)입니다!

2024-05-05 17:51 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/container/SoptAppContainer.kt
> +            .baseUrl("https://reqres.in/")
임시로 쓰는 api인 것 같아서 굳이 상수화를 안 하고 사용했습니다!

2024-05-05 17:56 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/container/SoptAppContainer.kt
> +        }
이 부분에 대해 약간 혼동이 있어서 일단 이렇게 만들어봤어요. 로그인 api를 호출할 때 userId를 응답으로 받아 해당 시점에 레트로핏 객체를 생성하도록 구현을 해야 하는데, 인터셉터에 userId를 넣을 방법이 마땅히 생각나지 않아 함수화를 시켰어요... 이 부분은 수정해서 다시 올리겠습니다!

2024-05-05 17:57 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginScreen.kt
>      val uiState = viewModel.uiState.collectAsState()
value 부분이 사라지는 게 확실히 깔끔하네요,, 적용해보겠습니다!

2024-05-05 17:59 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginScreen.kt
>      viewModel.checkCurrentStack(context = context, navController = navController)
LaunchedEffect로 하면 컴포저블이 호출될 때 딱 한번만 실행되는게 맞나요?
과거에 컴포저블 본문에서 로그를 찍었을 때 여러 번 실행되던 일이 생각나네요,,

2024-05-05 18:05 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginViewModel.kt
> +        _uiState.update { currentState ->
`_uiState`는 뷰모델 내에서만 접근이 가능합니다.
이 상태 변수의 값을 컴포저블에서 바꾸기 위해 update 메서드를 따로 선언했습니다!!

2024-05-05 18:08 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginViewModel.kt
> +                }
"새로고침"이나 "자동으로 뒤로 가기" 같은 기능을 추가하는 방향을 생각해봐야겠네요!

2024-05-05 18:09 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/profile/ProfileViewModel.kt
> +        })
구현 당시엔 그 의도가 맞았는데, 지금 보니까 뭐라도 표시해주는게 알맞겠네요!!
날카로운 지적 감사합니다~!!

2024-05-05 18:10 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/signup/SignUpViewModel.kt
> +        )
넵 제거하겠습니다~!!

2024-05-05 18:12 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/network/ApiFactory.kt
> +    lateinit var retrofitAfterLogin: AuthService
저장소로 구현하려다가 시간 부족으로 xml에서 작성한 코드를 급하게 가져왔습니다;;
중복되는 부분이 좀 있어서 그 부분은 수정해서 다시 PR을 올리도록 할게요!!

2024-05-05 18:16 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/network/ApiFactory.kt
> +}
authService에 인터셉터를 넣기엔 로그인 이후에 받아온 userId를 헤더에 추가할 수 없다고 판단하여, 로그인 이후에 새로운 ApiFactory 객체를 만들도록 구현했습니다! 

lateinit var을 사용하면 그런 문제가 발생하는군요..! Preference를 통해 구현을 하는 방법을 깨달아서, ServicePool과 ApiFactory 내에서 mainService와 관련된 객체들을 lazy로 초기화하도록 수정해보겠습니다~

2024-05-05 18:17 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeScreen.kt
> +        viewModel.fetchDatas(navController)
네비게이션도 컨텍스트와 비슷하게 뷰모델로 넘기지 않는 요소들 중 하나인가 보네요..
권장되지 않는 부분은 수정해서 올리겠습니다!!

2024-05-05 18:17 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeScreen.kt
> +        /*Image(
넵 명심하겠습니다!!

2024-05-05 18:24 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +    }
팩토리를 사용하여 뷰모델에 값을 넘겨주는 코드에요!
컴포저블에서 뷰모델을 선언할 때 다음과 같이 사용됩니다.
`viewModel: HomeViewModel = viewModel(factory = HomeViewModel.Factory)`

2024-05-05 18:28 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +)
- 이 부분은 몰랐네요,, 이것 때문에 문제가 있었는데 드디어 그 이유를 깨달았습니다! 당장 고쳐봐야겠네요~
- 널타입 변수를 의미하는 것이니 그게 맞겠네요!!
- 이것도 처음 알았어요! List뿐만 아니라 다른 컬렉션들도 emptyList()를 지원하나요?

2024-05-06 01:13 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/SoptAppContainer.kt
>  }
좋은 코드랩을 보셨군요! 수동 DI를 먼저 공부하시고 DI를 학습하시면 이후에 Dagger나 Dagger-Hilt를 학습하실때에도 훨씬 이해가 잘 되실겁니다.

다만 interface를 선언하고 SoptAppContainer를 따로 만드시는 이유에 대해서는 코드랩의 설계를 따라하신 것인가요, 아니면 석준님의 의도가 있어서 따로 만드신것인가요?

2024-05-06 01:14 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/SoptAppContainer.kt
> +            .baseUrl("https://reqres.in/")
사실 이 부분 저는 외부에 노출되도 되는 api라면 숨길필요가 없다고 생각하긴 합니다(다만 secret key가 있다면 숨겨야겠죠?)

2024-05-06 01:14 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/network/ApiFactory.kt
> +    lateinit var retrofitAfterLogin: AuthService
PR여기에 이어서 수정하셔도 괜찮을 것 같아요 :)

2024-05-06 01:16 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeScreen.kt
> +        viewModel.fetchDatas(navController)
왜 넘기지 않는 요소들이라고 생각하시나요? 권장되지 않는 부분은 왜 권장되지 않는 지도 같이 생각을 하셔야 이후에 다른 요소들이 추가될때에도 이걸 뷰에 넣어야 하는지/ViewModel에 넣어야 하는 로직인지 아니면 아예 분리되어야 하는 로직인지 구분할 수 있습니다.

2024-05-08 06:28 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/container/SoptAppContainer.kt
>  }
코드랩의 설계 따라 만들었습니다;;
AppContainer뿐만 아니라 저장소 클래스를 구현할 때도 인터페이스를 설계하더라구요.. 보면서 전체적인 클래스의 구조를 볼 수 있는 것 같아 따라해보았습니다!!

2024-05-08 06:28 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/container/SoptAppContainer.kt
> +    lateinit var retrofitAfterLogin: AuthService
변경했습니다!

2024-05-08 06:30 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +            Log.d(TAG, follow.toString())
제거 완료!

2024-05-08 06:30 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +    private fun fetchMemberInfo(memberId: String = "66") {
구조를 바꿔보았습니다!

2024-05-10 09:27 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/SoptAppContainer.kt
>  }
그러면 interface를 분리하는 이유에 대해서는 알고 만드신걸까요? 만약에 코드랩대로 코드를 따라하신 것이라면 이번 기회에 왜 인터페이스와 클래스를 구분해서 구현하는지에 대해 알아보시는 것도 좋을 것 같습니다.

2024-05-10 09:28 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +)
List, Set, Map 모두 emptyCollection 함수 지원합니다.

[참고 포스트](https://itandhumanities.tistory.com/76)

2024-05-10 09:29 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginScreen.kt
>      viewModel.checkCurrentStack(context = context, navController = navController)
딱 한번만 실행될까요? LaunchedEffect의 공식문서 설명을 읽어보시는 것을 권장드립니다.

2024-05-10 09:55 UTC, l2hyunwoo reviewed
고생하셨습니다! 코드 변경한 부분에 대해서 간략하게 리뷰를 남겨드립니다. 추가적으로 객체지향 혹은 아안드로이드 앱 아키텍처(or 이외 아키텍처)와 관련된 문서를 여러개 찾아보셔서 읽어보시는 것을 권장드립니다.

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/AuthRepository.kt
이런 구현패턴을 모바일 쪽에서는 "레포지터리 패턴"이라고 부릅니다. 레포지터리 패턴을 적용하면 어떠한 이점을 얻을 수 있을까요? 그리고 그 이점으로 비추어 보았을 때 현재의 구현이 최선이라고 생각하시나요? 이에 대한 의견 개진 부탁드립니다 :)

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/MemberRepository.kt
> +        }
로직상, Id가 null인 사람이 내려오면 이를 정상응답이라고 판단하는 거이 맞을까요?

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/UserRepository.kt
>      override suspend fun setUserProfile(user: User) {
suspend 적용할 이유가 있을까요?

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/UserRepository.kt
> +    override suspend fun getUserProfile(): User {
여기도 마찬가지

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/UserRepository.kt
> +    }
```suggestion
    override suspend fun getUserId() = sharedPreferences.getString(USER_ID_KEY, "").orEmpty()
```

코틀린 특성을 활용한다면 이렇게 짤 수도 있습니다. 다만 이는 개인 취향에 따라서 구현 방향이 달라지기에 취향껏 선택하시면 됩니다.

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/UserRepository.kt
> +    }
여기서 apply를 적용하시는 이유가 따로 있을까요?

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/container/UserRepository.kt
> +            Log.d(TAG, "userId: $userId")
로그는 PR 머지전에 찾아서 지워주시면 좋을 것 같아요. (의도하신게 아니라면)

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/network/AuthService.kt
Service의 반환형으로 전부 Response wrapper를 붙이셨는데 이유를 알 수 있을까요?

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/network/dto/ResponseFollowListDto.kt
> +    @SerialName("per_page")
네이밍 컨벤션 snake_case -> camelCase

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/network/dto/ResponseFollowListDto.kt
> +    val data:List<Follower>,
data라는 변수명이 해당 데이터가 어떤 것인지 잘 보여줄 수 있나요?

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeScreen.kt
> +    LaunchedEffect(null) {
null을 넣으셔도 괜찮습니다. 그런데 대부분의 경우에서는 Unit 혹은 true 넣더라구요. 코드 일관성 때문에 그런것이니 너무 신경쓰지 않으셔도 됩니다.

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeUiState.kt
> +        var follower: List<Follower> = listOf()
로딩상태에 이런 정보들을 담는 이유가 있을까요?

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +            result.fold(
```suggestion
            authRepository.getUserInfo().fold(
```

변수 인라인할 수 있으면 인라인으로 적어주세요

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginScreen.kt
> +    val uiState by viewModel.uiState.collectAsState()
```suggestion
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
```

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginUiState.kt
> +    val pw: String = "",
축약어 지양해주세요

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginScreen.kt
> +    }
getLiveData라고 주어졌으면 navController에서 이런 데이터들을 LiveData처럼 사용하라고 함수를 설계했을 거에요. 그런데 현재 코드를 보면 navController에서 제공해주는 의도와는 살짝 거리가 먼것처럼 사용하고 계신 것 같습니다.

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginViewModel.kt
> +    private val authRepository: NetworkAuthRepository
interface 타입이 아닌 class 타입으로 사용하신 이유가 있을까요?

2024-05-10 09:55 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/screens/profile/ProfileScreen.kt
> +            ?.getLiveData<String>(MainActivity.NAVIGATE_LOGIN_KEY)?.value
위의 리뷰와 같은 의견입니다.

2024-05-16 11:29 UTC, chattymin approved these changes
현우님께서 너무 자세하게 잘 달아주셔서 제가 더 할말이 없네욥...!
수정 하신 후 머지하시면 될거같습니다~

2024-05-18 04:50 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/container/AuthRepository.kt
이러한 패턴으로 테스트 용이성과 유지보수가 편리해진다고 알고 있어요 :)
현재 방법이 최선이라고 생각되진 않지만 일단 배운대로 구현해본 것입니다!

2024-05-18 04:57 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/container/MemberRepository.kt
> +        }
오 생각해보니 비정상 응답이 맞겠네요,,
runCatching을 쓰니까 `!!`을 써서 사용하거나 null 타입 체크를 넣으면 되겠네요!

2024-05-18 04:58 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/container/UserRepository.kt
>      override suspend fun setUserProfile(user: User) {
예전에 RoomDB와 같은 로컬DB를 사용할 때 코루틴을 사용해서 데이터를 저장하거나 불러오도록 구현하더라구요,,
SharedPreference도 비슷한 느낌으로 사용해보았습니다!!

2024-05-18 05:00 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/container/UserRepository.kt
> +    }
sharedPreference에 변경사항을 적용하기 위해선 `commit()` 또는 `apply()` 메서드를 호출해야 해서 사용했습니다!

2024-05-18 05:00 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/container/UserRepository.kt
> +            Log.d(TAG, "userId: $userId")
넵 찾아서 지울게요~

2024-05-18 05:02 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/network/dto/ResponseFollowListDto.kt
> +    val data:List<Follower>,
응답DTO의 변수명들은 필요에 알맞게 바꾸는게 좋겠네요!

2024-05-18 05:03 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeUiState.kt
> +        var follower: List<Follower> = listOf()
해당 정보들을 성공적으로 받아오는지를 로딩에서 확인해야 한다고 생각되서 담았습니다.

로딩 상태에서 api를 호출하고 성공적으로 데이터들을 받아오면 부울값들을 바꿔 상태 변화를 구현해보았어요!

2024-05-18 05:08 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginScreen.kt
> +    }
지난 번에 멘션하신 잘못된 상태변환 방법으로 인해 다음과 같이 구현하게 됐어요,,
조만간 뷰모델 부분을 손보도록 하겠습니다!

2024-05-18 05:08 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginViewModel.kt
> +    private val authRepository: NetworkAuthRepository
오 이 부분은 수정하겠습니다!

2024-05-24 08:07 UTC, merged