Feat/#9 week_xml4 필수과제 구현
NOW-SOPT-ANDROID/seokjun-lee pull request #12
Opened 2024-05-03 14:32 UTC by boiledEgg-s

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #9

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- [x] API 통신을 통한 회원가입 기능 구현
- [x] API 통신을 통한 로그인 기능 구현
- [x] API 통신을 통한 내정보 기능 구현
- [x] HomeFragment에 [Reqres](https://reqres.in/)에서 제공하는 MockData 연결
- [x] API 통신을 통한 비밀번호 변경 기능 구현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
https://github.com/NOW-SOPT-ANDROID/seokjun-lee/assets/101652649/e99c2bb5-edbc-448e-82da-80357237182d

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
예쁘게 봐주세요~ 칭찬 많이 해주세요!

2024-05-03 16:39 UTC, Marchbreeze approved these changes
안녕하세요! 4주차 과제 3조 코드리뷰로 참여하게 된 32기, 33기 안드로이드 수료한 김상호입니다 :)
- 코드리뷰에 담긴 질문들은 꼭 고쳐야한다고 말씀드리는게 아닙니다! 코드를 활용해보는 과정에서 생각을 담은 개발을 하기 위한 하나의 질문을 던져드린다고 생각해주세요 ㅎㅎ (고치세요!가 아니라… 이유가 궁금하거나 알고 썼나 궁금해서 질문드리는…것입니다)
- 안드로이드 전에도 하다가 오셨나요? YB 느낌이 딱히 들지 않는 코드입니다! 넘 잘하시네요
- 그래서 별로 고쳐주고 싶은 부분이 많지 않았네요..ㅎㅎ 본인 코드 스타일도 이미 있으신 것 같아서 이대로 계속 하시면 될 것 같아요!
- 더 질문이 있으시면 동민이 통해서 연락처 받아서 계속 연락주셔도 됩니다 ~~ 모든 조원분들 다 좋아요 깃허브 댓글도 알림뜨면 바로 찾아오겠습니다 ㅎㅎ
- 이정도면 A시드 받아서 리드로 동민이 기 죽여주세요! ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-05-03 16:39 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/feat/PreferenceManager.kt
> +                    phoneNum = getString(MBTI_PREF_KEY, null)?:"",
`?: ""` 와 같은 기능을 하는 `orEmpty()` 함수도 있답니다! 이것은 취향차이 ...

2024-05-03 16:39 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/login/LoginActivity.kt
> +    }
아니 그냥 ... 넘 깔끔한데요

2024-05-03 16:39 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/login/LoginViewModel.kt
> +)
물론 이것도 취향이긴 하지만, 어처피 폴더링이 login으로 잘 되어있기 때문에 class 마다 파일을 두는 편입니당

2024-05-03 16:39 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/login/LoginViewModel.kt
> +private const val TAG = "LoginViewModel"
요 친구는 어디서 사용되나요? private인데 눈이 침침해서 ... 깃허브로는 못찾겠어요
아래 class 내부에 const val이 선언되어 있는데 같이 두기에는 기능적으로 문제가 있나요?

2024-05-03 16:39 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/main/HomeFragment.kt
> +        val commonListAdapter = CommonListAdapter(sharedViewModel.followLiveData.value?.friendList?: mutableListOf())
binding을 백패킹으로 onDestroyView에서 해제해주는 것처럼, 어댑터도 또 하나의 클래스이기 때문에 메모리 누출을 방지하기 위해서는 백패킹으로 관리되는 것이 권장됩니다!
binding, adapter, dialog 등등 생명주기와 완벽하게 연결되지 않는 기능들은 모두 유의해주시는 것이 좋아요

2024-05-03 16:39 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/main/HomeFragment.kt
>              layoutManager = LinearLayoutManager(requireContext())
LinearLayoutManager 선언도 xml에서 진행할 수 있는 것 알고 계신가요?
(이 부분도 지극히 취향차이입니다)

2024-05-03 16:39 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/main/MainActivity.kt
>      private lateinit var binding: ActivityMainBinding
이러한 binding들도 모두 백패킹 처리해주는 것이 권장됩니당~

2024-05-03 16:39 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/main/MainActivity.kt
> +        }
이 로직은 viewmodel에서 값이 변경된 것을 observe한 후, 추가적인 UI 작업 없이 바로 다시 viewmodel 작업을 시행하는 것으로 보입니다. 볼필요한 액티비티와 뷰모델 간 통신으로 보여지는데요, 이러한 비즈니스 로직은 모두 뷰모델에서 처리해주는 것이 좋을 것 같습니다 !

2024-05-03 16:39 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/main/MainViewModel.kt
> +        ServicePool.followService.getFollow(page).enqueue(object : Callback<ResponseFollowListDto> {
authService는 lateinit으로 변수를 선언하고, followService는 변수 선언 없이 바로 서버통신을 진행하는 이유는 무엇인가요?

2024-05-03 16:39 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/main/MainViewModel.kt
> +    }
이 로직은 데이터 모델 변환 관련만 존재하는 것 같은데, 이러한 경우 조금 더 관련있는 ResponseFollowListDto 파일에 함께 함수를 두는 것은 어떨까요?

2024-05-03 16:39 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/main/MyPageFragment.kt
> +        initTextViews(sharedViewModel.liveData.value?.userData!!)
!! 의 사용은 최대한 피해야 합니다! 엘비스 연산자를 활용해주세요~

2024-05-03 16:39 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/main/MyPageFragment.kt
> +                startActivity(intent)
```suggestion
                Intent(this, PasswordActivity::class.java).apply{
                  startActivity(this)
                }
```
처럼 스코프 함수를 활용하면 불필요한 객체 생성을 줄일 수 있어요!

2024-05-03 16:39 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/network/dto/ResponseFollowListDto.kt
> +    val per_page:Int,
안드로이드에서는 변수명을 카멜 케이스로 작성해주시는 것을 권장합니다!
서버에서 다르게 오는 경우를 대응해주기 위해서 @SerialName 어노테이션을 활용하는 건데요, 카멜케이스 형태의 변수에 저장하는 것을 추천드려요 ~~
```suggestion
    @SerialName("per_page")
    val perPage: Int,
```

2024-05-05 11:24 UTC, chattymin requested changes
이미 나보다 잘하는거 같은데요....?
에잉 그만잘하세요

2024-05-05 11:24 UTC, chattymin commented on app/src/main/java/com/sopt/now/login/LoginActivity.kt
> +    }*/
사용하지 않는 친구는 지워두는게 좋아요~
물론 지금은 공부중이기때문에 나중에 쓰려고 했던거라면 주석으로 표시해두기!

2024-05-05 11:24 UTC, chattymin commented on app/src/main/java/com/sopt/now/login/LoginActivity.kt
> +                    Toast.LENGTH_SHORT).show()
이번에 저도 깜빡하고 안했는데 toast와 같은 것들은 확장함수로 빼면 계속해서 쓰기 편하답니다

2024-05-05 11:24 UTC, chattymin commented on app/src/main/java/com/sopt/now/main/MyPageFragment.kt
> +        initTextViews(sharedViewModel.liveData.value?.userData!!)
저는 null이 아닐경우에만 해당 함수를 실행시키는 방법을 주로사용합니다.
혹은 nullable한 상태로 함수로 넘긴 후, 함수 내부에서 처리해도 됩니다!
저는 상황에 따라 다르게 사용해용

null일때는 실행 안시키는게 나은 경우도 있고, 빈 값이라도 넣어주는게 나은 경우가 있어서 그런건 코드 짜면서 차차 파악해가면 좋을 것 같아요

2024-05-05 11:24 UTC, chattymin commented on app/src/main/java/com/sopt/now/network/AuthService.kt
> +}
getMemberInfo라고 쓴 것 처럼 signUp도 앞에 통신 방식을 붙여서 postSignUp으로 쓰는건 어떨까요?
이렇게 하면 추후 관리가 편해집니당

2024-05-05 11:24 UTC, chattymin commented on app/src/main/java/com/sopt/now/password/PasswordActivity.kt
> +    }
정말 사소하지만 중요한 규칙 중 하나가 "호출된 순서대로 선언되어있어야 한다" 라는것입니다.
현재 onCreate에서 initObserve가 initView보다 먼저 선언되어있습니다. 그렇다면 아래 함수를 작성할 때 initObserve가 initView보다 먼저 나와야 코드를 찾아가기 쉽습니다.

지금은 내부에 2개밖에 없지만 추후 앱이 커지면 많은 함수를 호출하게 되는데 그때 순서가 뒤죽박죽이라면 유지보수할 때 힘들어져용

2024-05-05 11:35 UTC, youjin09222 approved these changes
깔끔 그 자체.. 많이 배우고 갑니다👍👍

2024-05-05 11:46 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/login/LoginActivity.kt
> +            loginEtPw.setText("seokjun")
스코프 함수 사용 너무 좋네요👏👏

2024-05-05 11:55 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/password/PasswordViewModel.kt
> +                    )
오 에러를 다양하게 출력할 수 있네요!
errorBody, errorMessage, errorCode, errorHeaders, responseMessage 이런 식의 직관적인 변수명도 좋을 것 같아요!

2024-05-05 13:01 UTC, boiledEgg-s commented
> 안녕하세요! 4주차 과제 3조 코드리뷰로 참여하게 된 32기, 33기 안드로이드 수료한 김상호입니다 :)
> 
> * 코드리뷰에 담긴 질문들은 꼭 고쳐야한다고 말씀드리는게 아닙니다! 코드를 활용해보는 과정에서 생각을 담은 개발을 하기 위한 하나의 질문을 던져드린다고 생각해주세요 ㅎㅎ (고치세요!가 아니라… 이유가 궁금하거나 알고 썼나 궁금해서 질문드리는…것입니다)
> * 안드로이드 전에도 하다가 오셨나요? YB 느낌이 딱히 들지 않는 코드입니다! 넘 잘하시네요
> * 그래서 별로 고쳐주고 싶은 부분이 많지 않았네요..ㅎㅎ 본인 코드 스타일도 이미 있으신 것 같아서 이대로 계속 하시면 될 것 같아요!
> * 더 질문이 있으시면 동민이 통해서 연락처 받아서 계속 연락주셔도 됩니다 ~~ 모든 조원분들 다 좋아요 깃허브 댓글도 알림뜨면 바로 찾아오겠습니다 ㅎㅎ
> * 이정도면 A시드 받아서 리드로 동민이 기 죽여주세요! ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-05-05 13:06 UTC, boiledEgg-s commented
> 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴



> 안녕하세요! 4주차 과제 3조 코드리뷰로 참여하게 된 32기, 33기 안드로이드 수료한 김상호입니다 :)
> 
> * 코드리뷰에 담긴 질문들은 꼭 고쳐야한다고 말씀드리는게 아닙니다! 코드를 활용해보는 과정에서 생각을 담은 개발을 하기 위한 하나의 질문을 던져드린다고 생각해주세요 ㅎㅎ (고치세요!가 아니라… 이유가 궁금하거나 알고 썼나 궁금해서 질문드리는…것입니다)
> * 안드로이드 전에도 하다가 오셨나요? YB 느낌이 딱히 들지 않는 코드입니다! 넘 잘하시네요
> * 그래서 별로 고쳐주고 싶은 부분이 많지 않았네요..ㅎㅎ 본인 코드 스타일도 이미 있으신 것 같아서 이대로 계속 하시면 될 것 같아요!
> * 더 질문이 있으시면 동민이 통해서 연락처 받아서 계속 연락주셔도 됩니다 ~~ 모든 조원분들 다 좋아요 깃허브 댓글도 알림뜨면 바로 찾아오겠습니다 ㅎㅎ
> * 이정도면 A시드 받아서 리드로 동민이 기 죽여주세요! ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

상호님 반갑습니다 :D
너무 좋은 말만 해주셔서 몸 둘 바를 모르겠네요ㅎㅎ 그래도 서툰 부분이 보이면 가감없이 말해주세요~
앞으로 잘 부탁드립니다!!

2024-05-05 13:06 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/feat/PreferenceManager.kt
> +                    phoneNum = getString(MBTI_PREF_KEY, null)?:"",
오 훨씬 가독성이 좋을 것 같네요!! 써보겠습니다~

2024-05-05 13:07 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/login/LoginActivity.kt
> +    }
동민님한테 배웠습니다ㅎㅎ

2024-05-05 13:08 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/login/LoginViewModel.kt
> +)
클래스 파일을 따로 관리하는게 추후에 찾기에도 편할 것 같네요!! 참고하겠습니다~

2024-05-05 13:12 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/login/LoginViewModel.kt
> +private const val TAG = "LoginViewModel"
보통 로그 찍을 때 파일 별로 태그를 지정하는 습관이 있어서 저렇게 구현했습니다!
파일 별로 `TAG`라는 변수를 사용하다보니 private으로 선언해야 되더라구요,,
private 변수를 companion object에 넣을 필요가 없다고 생각해서 따로 빼놓았는데, 이제 보니 따로 빼놓을 필요도 없겠네요ㅎㅎ

2024-05-05 13:13 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/main/HomeFragment.kt
> +        val commonListAdapter = CommonListAdapter(sharedViewModel.followLiveData.value?.friendList?: mutableListOf())
그러면 binding을 해제하기 전에 리사이클러뷰에 부착된 어뎁터를 해제하도록 하면 될까요?

2024-05-05 13:25 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/main/MainViewModel.kt
> +        ServicePool.followService.getFollow(page).enqueue(object : Callback<ResponseFollowListDto> {
여기서 authService 변수는 로그인 api의 응답으로 받아온 userId값을 인터셉터의 헤더에 넣어 새로운 레트로핏 객체를 생성하여 초기화됩니다. 인터셉터는 레트로핏의 초기화 단계에서만 할당이 가능하다고 들어 이렇게 구현했어요,,
그에 반해 followService는 그런 제약사항이 없어서 ServicePool이란 싱글톤 객체를 통해 바로 접근할 수 있도록 구현했습니다!!

다음 코드가 ServicePool 객체에 네트워크서비스 객체를 선언한 방법입니다!
```Kotlin
object ServicePool {
    val authService = ApiFactory.create<AuthService>()
    val followService = ApiFactory.createFollow<FollowService>()

    lateinit var mainService: AuthService
    fun initMainService(memberId: String) {
        ApiFactory.createRetrofitWithMemberId(memberId)
        mainService = ApiFactory.retrofitAfterLogin
    }
}
```

2024-05-05 13:26 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/main/MainViewModel.kt
> +    }
넵 수정하겠습니다!!

2024-05-05 13:27 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/main/MyPageFragment.kt
> +        initTextViews(sharedViewModel.liveData.value?.userData!!)
위에서 배운 `orEmpty`를 써볼게요!!

2024-05-05 13:28 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/main/MyPageFragment.kt
> +                startActivity(intent)
`apply`의 경우 방금 생성한 객체를 다른 메서드나 변수 초기화에 사용하기 위해 사용하는 스코프인가 보네요. 더 자세히 알아보고 적용해보겠습니다!!

2024-05-05 13:30 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/password/PasswordViewModel.kt
> +                    )
그렇네요!! 참고하겠습니다~

2024-05-05 14:03 UTC, hyeumm approved these changes
역시...너무 잘하세요.. 같은 YB인데 너무 잘하시는거 아닌지
오늘도 감탄하고 갑니닷..!

2024-05-05 14:03 UTC, hyeeum commented on app/src/main/java/com/sopt/now/login/LoginViewModel.kt
> +        const val HEADER_NAME = "location"
location도 이렇게 동반 객체로 설정해두셨군요..!

2024-05-05 14:03 UTC, hyeeum commented on app/src/main/java/com/sopt/now/main/MainViewModel.kt
> +    private fun putUserDataInFollow() {
되게 함수명을 직관적으로 잘 작성하시네요..이건 꼭 배워가야겠다...!

2024-05-05 14:03 UTC, hyeumm commented on app/src/main/java/com/sopt/now/login/LoginActivity.kt
> +        )
오 리턴하는 방식이 매우 새로워요..!
궁금한 점이 있는데 여기서 return과 return@with 의 차이점이 무엇인가요...? with(binding)이 있어서 with을 사용하신건가요?? return label과 관련해서 찾아봤는데 제가 본 예제와 구조가 달라서 어떻게 해석해야하는지 몰라 질문합니다..!

2024-05-05 15:32 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/login/LoginViewModel.kt
> +private const val TAG = "LoginViewModel"
사용되지 않는 코드는 정리해주는 것이 좋긴 한데, 매 파일마다 설정을 해두는 코드 습관이라면 얘기가 다르네요~

2024-05-05 15:33 UTC, Marchbreeze commented on app/src/main/java/com/sopt/now/main/HomeFragment.kt
> +        val commonListAdapter = CommonListAdapter(sharedViewModel.followLiveData.value?.friendList?: mutableListOf())
어댑터도 똑같이 백패킹으로 _adppter로 설정하고, 바인딩처럼 onDestoryView에서 null 처리해주시면 됩니당

2024-05-12 12:37 UTC, chattymin approved these changes
너무 잘한다. 합세때도 활약 기대하겠습니다!!

2024-05-24 08:04 UTC, merged