Feat/#6 week_xml2 필수과제 구현
NOW-SOPT-ANDROID/seokjun-lee pull request #7
Opened 2024-04-13 05:09 UTC by boiledEgg-s

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #6 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- [x] 1주차 과제를 바텀 네비게이션과 연동 시키기.
- [x] 타인의 프로필과 대비되도록 내 프로필 디자인하기
- [x] 데이터는 최소 스크롤이 가능해야 하며, 스크롤시에는 내 프로필 또한 같이 스크롤이 되도록 하기
- [x] 로그아웃 버튼 구현
- [x] SharedPreference 구현을 통한 제일 최근 회원가입한 인원 정보 저장
- [x] 메인액티비티에서 뒤로가기를 누르는 경우 바로 앱 종료 

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
[xml_week2.webm](https://github.com/NOW-SOPT-ANDROID/seokjun-lee/assets/101652649/8326e982-289e-41ce-a9f9-d0f930c7067e)

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
열심히는 해봤지만 건드릴수록 뭔가 애매해지네요,,
날카로운 리뷰 부탁드립니다~ 아쉬운 점은 바로 수정해보도록 할게요!!

2024-04-13 16:56 UTC, chattymin requested changes
너무 잘하시네요
이만 하산하십쇼

2024-04-13 16:56 UTC, chattymin commented on app/src/main/java/com/sopt/now/feat/PreferenceManager.kt
> +        preferenceEditor.commit()
Scope함수를 사용하면 불필요한 반복을 줄일 수 있을 것 같아요!!

2024-04-13 16:56 UTC, chattymin commented on app/src/main/java/com/sopt/now/login/LoginActivity.kt
> +        binding.apply {
여러 scope 함수중에 apply를 사용하신 이유가 있을까요??
[사용법](https://velog.io/@rhkswls98/Android-Kotlin-apply-with-let-also-run-%EC%A0%95%EB%A6%AC)을 보시고 상황에 맞게 사용하시는 것을 추천드립니다!

2024-04-13 16:56 UTC, chattymin commented on app/src/main/java/com/sopt/now/login/LoginActivity.kt
> +        getIntentResult.launch(intent)
요것두 Scope함수를 사용하면 간략하게 할 수 있습니다!

2024-04-13 16:56 UTC, chattymin commented on app/src/main/java/com/sopt/now/main/HomeFragment.kt
> +        ),
viewModel을 배운 김에 이런 모든 데이터들은 viewModel에서 처리하게 해봅시다.

activity or fragement는 ui와 관련된 부분만 처리하고, 모든데이터는 viewModel에서 관리한다면 추후 유지보수하기 좋은 코드가 될 수 있답니다.

2024-04-13 16:56 UTC, chattymin commented on app/src/main/java/com/sopt/now/main/MyPageFragment.kt
> +    val onClickLogoutButton: MainActivity.OnClickLogoutButton): Fragment() {
중괄호는 어디서 닫히는건가요...?

2024-04-13 16:56 UTC, chattymin commented on app/src/main/java/com/sopt/now/main/MyPageFragment.kt
> +        }
apply를 사용하신 이유가 있을까요??
위에도 적어뒀지만 많은 scope 함수중에서 해당 scope함수를 사용하는 이유를 알고 사용하셔야 합니다.

2024-04-13 16:56 UTC, chattymin commented on app/src/main/java/com/sopt/now/models/User.kt
> +): Serializable{}
Serializable을 쓰신 이유와, 이번에 중괄호를 왜 붙이신걸까용?

2024-04-13 16:56 UTC, chattymin commented on app/src/main/java/com/sopt/now/signup/SignUpActivity.kt
> +            pw.length !in 8..12 -> R.string.toast_signup_check_pw
[Magic Number](https://velog.io/@hwisaac/%EB%A7%A4%EC%A7%81%EB%84%98%EB%B2%84) 사용을 지양합시다!!
지금은 이해가 가겠지만, 나중에 본다면 가독성이 상당히 떨어지게 됩니다.
또한 추후 값을 수정하게 된다면 해당 값을 쓴 곳을 찾아다니는 것 보다, 상수를 모아둔 곳에서 수정을 하는 것이 훨씬더 용이해집니당

2024-04-13 16:56 UTC, chattymin commented on app/src/main/res/layout/item_friend.xml
> +        android:text="이석준"
이 값은 추후 덮어쓰기 될 값일텐데 이런 것은 tools를 활용하시면 좋습니다!
서버로부터 값이 로딩되기 전 불필요한 값이 나와있는 것을 막고, xml 코드 짤때는 불편함 없이 가능하답니당

2024-04-13 16:56 UTC, chattymin commented on app/src/main/res/layout/item_friend.xml
> +        android:maxLines="1"
maxLines가 1이라면 화면을 넘어갈 정도로 text의 길이가 길다면 어떻게 처리될까요??
직접적으로 선언해주는 것도 좋을 것 같습니담

2024-04-13 18:56 UTC, chanubc reviewed
2년사이에 무슨일이 있었던거죠? 진짜 일취월장 하셨네요

추가로 코멘트를 드리자면
멀티 리사이클러뷰 구현시  ViewObject 에서 CommonItem을 타고 들어 가는 구조인데

개인적으로 CommonItem은 없어도 되는것 같습니다!
ViewObject를 리사이클러뷰의 data class로 사용해도 될것 같아요!

그러면 CommonviewType이나 CommonViewHolder에서 abstract bind함수 등등 몇가지 코드를 줄일 수 있을 것 같습니다!

ViewHolder도 한 클래스 안에서 선언 하는 것 보다 담당하는 item별로 분리해서 따로 class를 만드는게 더 효율적일 수 도 있다는 생각이 들어서요!!

개인적인 의견입니다.
과제 너무 잘하셨네요ㄷㄷ 저 그냥 밥좀 사주세요 배고파여

2024-04-13 18:56 UTC, chanubc commented on app/src/main/java/com/sopt/now/feat/PreferenceManager.kt
> +
ㄷㄷ그간 무슨 일이 있었던 겁니까
compaion object 블록은 보통 클래스 최 하단에 작성해요!

 미쳤네요ㄷㄷ

2024-04-13 18:56 UTC, chanubc commented on app/src/main/java/com/sopt/now/login/LoginActivity.kt
> +        binding.apply {
지교수님의 흔적인가..ㅋㅋㅋ
,binding은 apply보단 with가 적합해요!

2024-04-13 18:56 UTC, chanubc commented on app/src/main/java/com/sopt/now/main/adapter/CommonViewHolder.kt
> +    abstract fun bind(item: CommonItem)
이런 아이디어도 있군요!

2024-04-16 15:55 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/feat/PreferenceManager.kt
> +        preferenceEditor.commit()
오 그렇네요~ 이런 객체에 대한 Scope 함수는 with가 제일 적합한건가요??

2024-04-16 15:57 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/login/LoginActivity.kt
> +        binding.apply {
건대 컴공생에게 그린조아는 문신이죠ㅋㅋㅋ
scope에 대해 더 자세히 공부해야겠네요;;

2024-04-16 15:57 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/login/LoginActivity.kt
> +        getIntentResult.launch(intent)
넵 수정해보도록 할게요~

2024-04-16 15:59 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/main/MyPageFragment.kt
> +    val onClickLogoutButton: MainActivity.OnClickLogoutButton): Fragment() {
엥?? 푸시 전에 실수로 지웠나보네요😖
수정해서 올리겠습니다!!

2024-04-16 16:06 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/models/User.kt
> +): Serializable{}
원인 모를 에러가 나길래 여기저기 수정하다가 중괄호를 넣었나보네요😓

Serializable은 성능 이런 것보단 더 많이 써봐서 넣었어요,, 
[찾아보니까](https://velog.io/@jaeyunn_15/Android-Parcelable-vs-Serializable) Serializable은 자바 인터페이스이고 Parceable은 Android SDK 인터페이스네요.
Serializable은 시스템 비용을 많이 발생시키고, Parceable은 구현 및 유지보수 비용이 많이 든다고도 하네요.

2024-04-16 16:07 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/signup/SignUpActivity.kt
> +            pw.length !in 8..12 -> R.string.toast_signup_check_pw
넵 수정해볼게요!

2024-04-16 16:10 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/feat/PreferenceManager.kt
> +
같이 배운거면서 새삼스레 뭘 그러십니까~

companion 위치 명심하겠습니다🫡 ^^7

2024-04-18 16:34 UTC, chattymin commented on app/src/main/java/com/sopt/now/feat/PreferenceManager.kt
> +        preferenceEditor.commit()
넹~ 정답입니당

2024-04-21 12:42 UTC, youjin09222 approved these changes
와.. 너무 잘하시는데요😲

2024-04-21 12:47 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/ext/IntentExt.kt
> +}
오 확장 함수.. Serializable 객체를 가져오는 방법이 신기하네요😲

2024-04-21 12:51 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/feat/PreferenceManager.kt
> +}
저도 다음부터 SharedPreferences를 사용해서 데이터 관리를 해야겠어요!

2024-04-21 13:01 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/main/adapter/ViewObject.kt
> +}
오 이렇게 하면 ViewObject로 두 데이터 클래스에 접근 가능하겠네요!

2024-04-21 13:08 UTC, hyeumm approved these changes
배울 점이 많은 코드였습니다...

2024-04-21 13:08 UTC, hyeumm commented on app/src/main/java/com/sopt/now/main/HomeFragment.kt
> +        mockFriendList.add(0, userItem)
이런식으로 유저데이터를 추가하는 방법도 있군요!

2024-04-21 13:08 UTC, hyeumm commented on app/src/main/java/com/sopt/now/login/LoginActivity.kt
> +    }
오 스코프 함수를 사용하니 정말 간결해보여요..!

2024-04-27 01:47 UTC, chattymin approved these changes
LGTM!
찬우님이 말씀해주셨던것처럼 companion object가 최하단에 가도록 수정 해주세용~

2024-04-28 14:10 UTC, merged