Feat/#5 week_compose2 필수과제 구현
NOW-SOPT-ANDROID/seokjun-lee pull request #8
Opened 2024-04-16 15:52 UTC by boiledEgg-s

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #5 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 1주차 과제를 바텀 네비게이션과 연동 시키기.
- 타인의 프로필과 대비되도록 내 프로필 디자인하기
- 데이터는 최소 스크롤이 가능해야 하며, 스크롤시에는 내 프로필 또한 같이 스크롤이 되도록 하기
- 로그아웃 버튼 구현 (누르면 로그인 화면으로 이동)
- 메인화면에서 뒤로가기를 누르는 경우 바로 앱 종료 
- (추가) SharedPreference 구현을 통한 제일 최근 회원가입한 인원 정보 저장
- (추가) 뷰모델 구현
- (추가) 네비게이션 구현 

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
[compose_week2.webm](https://github.com/NOW-SOPT-ANDROID/seokjun-lee/assets/101652649/2800dbe5-0fd5-4622-853c-da140a35d7c2)

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
이것저것 넣어봤습니다,, 뭔가 많이 해보려고 했지만 지저분하기만 하네요😓
리뷰 달아주시면 후딱 수정해보이겠슴다~

2024-04-18 16:04 UTC, chattymin requested changes
그만잘해.. 왤케 잘해...

2024-04-18 16:04 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/container/UserRepository.kt
> +    }
오... 님 좀 멋지네요

2024-04-18 16:04 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/ui/navigation/ScreenDestinations.kt
> +}
interface와 object 구조로 작성하신 이유가 있나용??

2024-04-18 16:04 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeScreen.kt
> +    BackHandler { viewModel.onBackPressed(navController) }
ui와 관련이 없는 코드는 `LaunchedEffect`로 묶어주는 것이 좋습니다!

2024-04-18 16:04 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/ui/screens/login/LoginViewModel.kt
> +    }
사소하긴 하지만, 기본값을 id error로 두고 success, pw error로 바꾸는 것 보다 success를 기본값으로 두고 error들과 관련된 string으로 바꾸는게 더 직관적일 것 같습니다

2024-04-21 03:57 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/ui/navigation/ScreenDestinations.kt
> +}
안드로이드 사이트에서 공부할 때 배운 구조인데, 이렇게 사용한 의도는 정확히는 모르겠네요,,😓😓

각 스크린 파일마다 object로 선언했던 기존 구조에서 `ScreenDestinations.kt` 파일을 새로 만들어서 관리해봤어요.
인터페이스를 통해 기본 틀을 잡고 object를 통해 싱글톤 구조로 선언하여 하나의 객체만을 생성해 파일 어느 곳에서든 호출할 수 있도록 한 것이 아닐까 추측하고 있습니다!!

2024-04-21 12:55 UTC, hyeumm approved these changes
너무 잘하시는 거 아니신가요
YB 아니죠?

2024-04-21 12:55 UTC, hyeumm commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeScreen.kt
> +                ScreenWithImage(imageRes = R.drawable.ic_broken_image, contentDescription = "Error")
상태에 따라서 다른 화면이 나타나는군요..역시..섬세하십니다

2024-04-21 12:55 UTC, hyeumm commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeViewModel.kt
> +            selfDescription = "소주잔 3조 화이팅!!",
화이팅!

2024-04-21 12:55 UTC, hyeumm commented on app/src/main/java/com/sopt/now/compose/ui/screens/profile/ProfileScreen.kt
> +private const val TAG = "ProfileScreen"
태그를 사용하는 이유가 궁금합니다..! 로그에서 사용하기 위함일까요..?!

2024-04-21 13:12 UTC, youjin09222 approved these changes
ㅇ..왜 이렇게 잘하시는 거예요...

2024-04-21 13:13 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/compose/container/UserRepository.kt
> +    }
와 이런 식으로 데이터 관리를 할 수 있군요..?
sharedPreferences! 확실히 배우고 갑니다!

2024-04-21 13:25 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeScreen.kt
> +                ScreenWithImage(imageRes = R.drawable.ic_broken_image, contentDescription = "Error")
와 여기 대박인데요..? 상태 별로 다른 화면을 보여주다니!! 진짜 대단하십니다..

2024-04-21 13:28 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/compose/ui/composables/ButtonComposable.kt
재사용성을 높이기 위해 버튼을 Composable 함수로 구현하셨네요!
저도 다음부터 이렇게 해봐야겠습니다!

2024-04-21 18:12 UTC, chanubc reviewed
코드리뷰 달러왔다 도망갑니다
방학동안 대체 무슨 강의를 들으신 겁니까?

2024-04-27 01:51 UTC, chattymin approved these changes
LGTM!!

눈물나게 잘하시네요

2024-04-27 01:51 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/ui/screens/home/HomeScreen.kt
> +    LaunchedEffect(navController){
key값을 navController로 설정한 이유가 있을까용??

2024-04-28 14:09 UTC, merged